const nombrePeliculas = [
    { id: 1, titulo: 'TITANIC' },
    { id: 2, titulo: 'EL RESPLANDOR' },
    { id: 5, titulo: 'UN ELEFANTE CON TROMPA ENORME' },
    { id: 6, titulo: 'TIEMPO DE VENGANZA' },
    { id: 7, titulo: 'EL INQUILINO' },
    { id: 8, titulo: 'LOS ESTUDIANTES NO SON VIRGENES' },
    { id: 9, titulo: 'LLUVIA NEGRA' },
    { id: 10, titulo: 'EL MAGO DE OZ' },
    { id: 11, titulo: 'MAS ALLA DEL HONOR' },
    { id: 12, titulo: 'HORA DE MATAR' },
    { id: 13, titulo: 'SPAGHETTI A LA MEDIANOCHE' },
    { id: 14, titulo: 'SEÑORA DE NADIE' },
    { id: 15, titulo: 'OPERACION DIAMANTES' },
    { id: 16, titulo: 'EL GRAN DUELO' },
    { id: 17, titulo: 'LOS DIOSES DEBEN ESTAR LOCOS' },
    { id: 18, titulo: 'MATADOR' },
    { id: 19, titulo: 'RICITOS DE ORO' },
    { id: 20, titulo: 'LA HORA DEL ASESINO' },
    { id: 21, titulo: 'DIOS PERDONA, YO NO' },
    { id: 22, titulo: 'LA NOCHE QUE HICIMOS EL HURTO' },
    { id: 23, titulo: 'FUEGO Y LLUVIA' },
    { id: 24, titulo: 'FUGA NOCTURNA' },
    { id: 25, titulo: 'DESPEDIDA DE SOLTERO' },
    { id: 26, titulo: 'LA ULTIMA NAVIDAD' },
    { id: 27, titulo: 'SAMURAI' },
    { id: 28, titulo: 'CADENAS CALIENTES' },
    { id: 29, titulo: 'MANOS TORPES' },
    { id: 30, titulo: '¿QUE HACIAS CUANDO SE APAGO LA LUZ?' },
    { id: 31, titulo: 'EN FAMILIA' },
    { id: 32, titulo: 'LA ALFOMBRA MAGICA' },
    { id: 33, titulo: 'LA SEDUCCION' },
    { id: 34, titulo: 'LA LLAMADA DEL DIABLO' },
    { id: 35, titulo: 'EL VUELO DE LA PALOMA' },
    { id: 36, titulo: 'BRAZOS DE TERCIOPELO' },
    { id: 37, titulo: 'UN AMIGO PURA SANGRE' },
    { id: 38, titulo: 'LA CONEXION' },
    { id: 39, titulo: 'LA MASCARA DE LA MUERTE' },
    { id: 40, titulo: 'EL BARCO DE LOS LOCOS' },
    { id: 41, titulo: 'EL PAJARO CANTA HASTA MORIR' },
    { id: 42, titulo: 'TRES MORDISCOS DE LA MANZANA' },
    { id: 43, titulo: 'RIVALES A MUERTE' },
    { id: 44, titulo: 'LA PIEDRA SANGRIENTA' },
    { id: 45, titulo: 'SHAMPOO' },
    { id: 46, titulo: 'CARA A CARA AL DESNUDO' },
    { id: 47, titulo: 'EL CAPITAN FURIA' },
    { id: 48, titulo: 'CRUZ DE HIERRO' },
    { id: 49, titulo: 'ABAJO LOS HOMBRES' },
    { id: 50, titulo: 'QUE BUENA MADRE ES MI PADRE' },
    { id: 51, titulo: 'PALABRAS DE LIBERTAD' },
    { id: 52, titulo: 'SALUDOS AMIGOS' },
    { id: 53, titulo: 'CONTACTO EN FRANCIA' },
    { id: 54, titulo: 'PASO SANGRIENTO' },
    { id: 55, titulo: 'MI VILLANO FAVORITO' },
    { id: 56, titulo: 'LA FURIA DE LA SERPIENTE' },
    { id: 57, titulo: 'EL PROXIMO HOMBRE' },
    { id: 58, titulo: 'INFIERNO' },
    { id: 59, titulo: 'LOS TRES CHIFLADOS' },
    { id: 60, titulo: '2000 LENGUA DE VIAJE SUBMARINO' },
    { id: 61, titulo: 'TRAMPA MORTAL' },
    { id: 62, titulo: 'MISION SALVAR LA TIERRA' },
    { id: 63, titulo: 'EL QUE NO CORRE VUELA' },
    { id: 64, titulo: 'EL SACERDOTE' },
    { id: 65, titulo: 'LA LOBA Y LA PALOMA' },
    { id: 66, titulo: 'LA GUERRA GAUCHA' },
    { id: 67, titulo: 'EL DORADO' },
    { id: 68, titulo: 'VERANO DEL 42' },
    { id: 69, titulo: 'EL COSTO DEL EXITO' },
    { id: 70, titulo: 'LOS CAZADORES DEL ARCA PERDIDA' },
    { id: 71, titulo: 'JUEGO LETAL' },
    { id: 72, titulo: 'CUANDO ES PRECISO SER HOMBRE' },
    { id: 73, titulo: 'HOGAR DULCE HOGAR' },
    { id: 74, titulo: 'CEMENTERIO DE ANIMALES' },
    { id: 75, titulo: 'LA ARDILLA TRAVIESA' },
    { id: 76, titulo: 'DOS TIPOS DUROS' },
    { id: 77, titulo: 'LA GUERRA DE LAS GALAXIAS' },
    { id: 78, titulo: 'EL ASESINO Y LA DAMA' },
    { id: 79, titulo: 'LOS PERROS DE PAJA' },
    { id: 80, titulo: 'ISLAS SALVAJES' },
    { id: 81, titulo: 'LA RENUNCIA' },
    { id: 82, titulo: 'LAZOS DE SANGRE' },
    { id: 83, titulo: 'PRIMER AMOR' },
    { id: 84, titulo: 'BUSCO MI DESTINO' },
    { id: 85, titulo: 'EL RUISEÑOR' },
    { id: 86, titulo: 'EL INVESTIGADOR PRIVADO' },
    { id: 87, titulo: 'LA FUERZA DEL DEMONIO' },
    { id: 88, titulo: 'ENTRE LA RUBIA Y LA MORENA' },
    { id: 89, titulo: 'CON LOS OJOS CERRADOS' },
    { id: 90, titulo: 'CORAZON DE PIEDRA' },
    { id: 91, titulo: 'EL FRANCOTIRADOR' },
    { id: 92, titulo: 'EL CANTOR DE JAZZ' },
    { id: 93, titulo: 'ESPERANDO EL MILAGRO' },
    { id: 94, titulo: 'DERECHO A MORIR' },
    { id: 95, titulo: 'EL RETORNO DEL MONSTRUO DEL PANTANO' },
    { id: 96, titulo: 'LAVADO DE CEREBRO' },
    { id: 97, titulo: 'BARBA AZUL' },
    { id: 98, titulo: '5 TENEDORES' },
    { id: 99, titulo: 'EL DEPENDIENTE' },
    { id: 100, titulo: 'EL ARBOL MAGICO' },
    { id: 101, titulo: ' EL PECADO MORTAL' },
    { id: 102, titulo: 'UNA PEQUEÑA MUSICA NOCTURNA' },
    { id: 103, titulo: 'ROSA CAFE' },
    { id: 104, titulo: 'GRACIAS POR EL FUEGO' },
    { id: 105, titulo: 'EL TEMPLO DEL FUEGO' },
    { id: 106, titulo: 'FANTASMA POR CASUALIDAD' },
    { id: 107, titulo: 'LOS COWBOYS' },
    { id: 108, titulo: 'LOS CUATRO LOCOS NACIDOS EL 4 DE JULIO' },
    { id: 109, titulo: 'AMIGOS INSEPARABLES' },
    { id: 110, titulo: 'UN PASO EN FALSO' },
    { id: 111, titulo: 'EL BLANCO, EL AMARILLO Y EL NEGRO' },
    { id: 112, titulo: 'NO HAGAN OLAS' },
    { id: 113, titulo: 'CARTAS DE AMOR' },
    { id: 114, titulo: 'LOS PEQUEÑOS DRAGONES' },
    { id: 115, titulo: 'LA BATALLA DE ARGELIA' },
    { id: 116, titulo: 'DISPARA PRIMERO... RIE DESPUES' },
    { id: 117, titulo: 'CRIMEN POR MUERTE' },
    { id: 118, titulo: 'LA LECCION DE PIANO' },
    { id: 119, titulo: 'ESCAPE AL FUTURO' },
    { id: 120, titulo: 'BUSCADO VIVO O MUERTO' },
    { id: 121, titulo: 'REGALO DIABOLICO' },
    { id: 122, titulo: 'DEL ROSAS AL AMARILLO' },
    { id: 123, titulo: 'LA NOVENA SINFONIA' },
    { id: 124, titulo: 'EL HIJO DE LA PANTERA ROSA' },
    { id: 125, titulo: 'BANDIDOS DEL TIEMPO' },
    { id: 126, titulo: 'EL VIOLINISTA EN EL TEJADO' },
    { id: 127, titulo: 'LA MUJER, EL TORERO Y EL TORO' },
    { id: 128, titulo: 'CAFE DE PUERTO' },
    { id: 129, titulo: 'LOS MOCHILEROS' },
    { id: 130, titulo: 'FUERTE APACHE' },
    { id: 131, titulo: 'UNA DAMA ENTRE VAQUEROS' },
    { id: 132, titulo: 'UNA HISTORIA DIFERENTE' },
    { id: 133, titulo: 'EXODO' },
    { id: 134, titulo: 'PELEDORES IMPLACABLES' },
    { id: 135, titulo: 'PAGO A CUENTA DE LA MUERTE' },
    { id: 136, titulo: 'EL FANTASMA DE LA OPERA' },
    { id: 137, titulo: 'DE PRISA, DE PRISA' },
    { id: 138, titulo: 'Y MAÑANA SERAN HOMBRES' },
    { id: 139, titulo: 'EL LIBRO DE LA SELVA' },
    { id: 140, titulo: 'LA SOPLONA' },
    { id: 141, titulo: 'CON LA SOGA AL CUELLO' },
    { id: 142, titulo: 'EL ALEGRE DIVORCIADO' },
    { id: 143, titulo: 'MANTO NEGRO' },
    { id: 144, titulo: 'DUMBO' },
    { id: 145, titulo: 'PISANDO FUERTE' },
    { id: 146, titulo: 'FRANKENSTEIN' },
    { id: 147, titulo: 'JUEGOS EN LA NIEVE' },
    { id: 148, titulo: 'SIN TESTIGO' },
    { id: 149, titulo: 'UN LEON EN MI CAMA' },
    { id: 150, titulo: '¿DONDE ESTA MI HIJA?' },
    { id: 151, titulo: 'UN PUEBLO LLAMADO INFIERNO' },
    { id: 152, titulo: 'EL DORMILON' },
    { id: 153, titulo: 'LAS NIÑAS MADRES' },
    { id: 154, titulo: 'EL IMPERIO DEL SOL' },
    { id: 155, titulo: 'CALIENTE AL ROJO VIVO' },
    { id: 156, titulo: 'LA MANZANA' },
    { id: 157, titulo: 'LA EJECUCION' },
    { id: 158, titulo: 'UN EXTRAÑO ESPERA' },
    { id: 159, titulo: 'EL ULTIMO GUERRERO ESPACIAL' },
    { id: 160, titulo: 'MESA PARA CINCO' },
    { id: 161, titulo: 'EL RING' },
    { id: 162, titulo: 'ANTEOJITO Y ANTIFAZ' },
    { id: 163, titulo: 'EL LATIGO DEJA SU MARCA' },
    { id: 164, titulo: 'UN DEMONIO Y UNA CANCION' },
    { id: 165, titulo: 'LA MUJER DEL JUGADOR' },
    { id: 166, titulo: 'SUR' },
    { id: 167, titulo: 'YO ESTOY CON LOS HIPOPOTAMOS' },
    { id: 168, titulo: 'CIUDAD ARDIENTE' },
    { id: 169, titulo: 'EL DUO INVICIBLE' },
    { id: 170, titulo: 'LAS LOBAS' },
    { id: 171, titulo: 'PROHIBIDA OBSESION' },
    { id: 172, titulo: 'MISTERIO EN LA ISLA DE LOS MONSTRUOS' },
    { id: 173, titulo: 'LA PRISION DE LA MUERTE' },
    { id: 174, titulo: 'LA HEMBRA APACHE' },
    { id: 175, titulo: 'BUENOS MUCHACHOS' },
    { id: 176, titulo: 'BODAS DE SANGRE' },
    { id: 177, titulo: 'LA MANO NEGRA' },
    { id: 178, titulo: 'EL AGUILA HA LLEGADO' },
    { id: 179, titulo: 'LOCO POR LA MUSICA' },
    { id: 180, titulo: 'LA LADRONA' },
    { id: 181, titulo: 'LA BAMBA' },
    { id: 182, titulo: 'RESCATE INFERNAL' },
    { id: 183, titulo: 'A UN PASO DE LA MUERTE' },
    { id: 184, titulo: 'CABALGATA INFERNAL' },
    { id: 185, titulo: 'DIAS DE GLORIA' },
    { id: 186, titulo: 'EL VIAJE INCREIBLE' },
    { id: 187, titulo: 'INFIERNO EN EL MEDIO ORIENTE' },
    { id: 188, titulo: 'ME SOBRA UNA MUJER' },
    { id: 189, titulo: 'EL VESTIDOR' },
    { id: 190, titulo: 'LA GRAN AMENAZA' },
    { id: 191, titulo: 'OPERACION TELEFONO' },
    { id: 192, titulo: 'EL JUEGO DE LOS BRUJOS' },
    { id: 193, titulo: 'EL HOMBRE, LA MUJER Y EL DINERO' },
    { id: 194, titulo: 'SANGRE Y ARENA' },
    { id: 195, titulo: 'EL BRUJO' },
    { id: 196, titulo: 'ALIEN, EL OCTAVO PASAJERO' },
    { id: 197, titulo: 'BARRIO PELIGROSO' },
    { id: 198, titulo: 'DETECTIVE PIEPLANO' },
    { id: 199, titulo: 'AUTOPISTA' },
    { id: 201, titulo: 'LA BELLA DURMIENTE' },
    { id: 202, titulo: 'DEPREDADOR' },
    { id: 203, titulo: 'EL FUERTE INFERNAL' },
    { id: 204, titulo: 'EL MANOSANTA' },
    { id: 205, titulo: 'LOS GRITOS DEL SILENCIO' },
    { id: 206, titulo: 'EL CRISTAL ENCANTADO' },
    { id: 207, titulo: 'CIUDAD SIN LEY' },
    { id: 208, titulo: 'JUEGO LIMPIO' },
    { id: 209, titulo: 'PANDILLERO EN APURO' },
    { id: 210, titulo: 'CONFESIONES DE UN HOMBRE CASADO' },
    { id: 211, titulo: 'EL PRICIPITO' },
    { id: 212, titulo: 'MAS ALLA DE LAS ESTRELLAS' },
    { id: 213, titulo: 'CLUB DE ENCUENTROS' },
    { id: 214, titulo: 'LA JAURIA HUMANA' },
    { id: 215, titulo: 'JUSTICIA' },
    { id: 216, titulo: 'LA MANO' },
    { id: 217, titulo: 'BRUTOS, SUCIOS Y MALOS' },
    { id: 218, titulo: 'EL GRITO DE LA LECHUZA' },
    { id: 219, titulo: 'LOS INVASORES VIKINGOS' },
    { id: 220, titulo: 'ARCHIVO CONFIDENCIAL' },
    { id: 221, titulo: 'DUELO AL SOL' },
    { id: 222, titulo: 'ALTA SOCIEDAD' },
    { id: 223, titulo: 'DOS VECES EN LA VIDA' },
    { id: 224, titulo: 'RAMBO' },
    { id: 225, titulo: 'EL MUNDO EN LLAMAS' },
    { id: 226, titulo: 'VIAJE INSOLITO' },
    { id: 227, titulo: 'UN MUCAMO EN MI CASA' },
    { id: 228, titulo: 'EL PAJARO LOCO Y SUS AMIGOS' },
    { id: 229, titulo: 'VENGANZA' },
    { id: 230, titulo: 'EL ALQUIMISTA' },
    { id: 231, titulo: 'EL ARABE' },
    { id: 232, titulo: 'CINTA NEGRA CONTRA MAFIA' },
    { id: 233, titulo: 'SIERRA ALTA' },
    { id: 234, titulo: 'LA SEMILLA DEL DIABLO' },
    { id: 235, titulo: 'EL PRINCIPIANTA' },
    { id: 236, titulo: 'EL VOLAR ES PARA PAJAROS' },
    { id: 237, titulo: 'EL OSO' },
    { id: 238, titulo: 'CORREO ESPACIAL' },
    { id: 239, titulo: 'EL PLANETA DE LOS SIMIOS' },
    { id: 240, titulo: 'ASI AMA UNA MUJER' },
    { id: 200, titulo: 'DE NIÑAS A MUJERES' },
    { id: 241, titulo: 'MIS CINCO PERSONALIDADES' },
    { id: 242, titulo: 'EL HOMBRE DE MIMBRE' },
    { id: 243, titulo: 'AVECES SIN RUMBO' },
    { id: 244, titulo: 'MALA PARA' },
    { id: 245, titulo: 'LABERINTO' },
    { id: 246, titulo: 'DOS CONTRA TODOS' },
    { id: 247, titulo: 'ALMUERZO FATAL' },
    { id: 248, titulo: 'DIAS DE RADIO' },
    { id: 249, titulo: 'LAS SANDALIAS DEL PESCADOR' },
    { id: 250, titulo: 'LADRONA DE ESTRELLAS' },
    { id: 251, titulo: 'FURIA SILENCIOSA' },
    { id: 252, titulo: 'LA MARCA DE LA PANTERA' },
    { id: 253, titulo: 'CUATRO MUJERES' },
    { id: 254, titulo: 'FIN DE SEMANA SALVAJE' },
    { id: 255, titulo: 'CAMINO AL INFIERNO' },
    { id: 256, titulo: 'MANICOMIO' },
    { id: 257, titulo: 'ALTO SECRETO' },
    { id: 258, titulo: 'LA BICLETA SON PARA EL VERANO' },
    { id: 259, titulo: 'ASALTO AL BANCO CENTRAL' },
    { id: 260, titulo: 'HUMO DE MARIHUANA' },
    { id: 261, titulo: 'SOMBRERO DE COPA' },
    { id: 262, titulo: 'ABIERTO DE DIA Y NOCHE' },
    { id: 263, titulo: 'LA SIRENITA' },
    { id: 264, titulo: 'PELEAR O MORIR' },
    { id: 265, titulo: 'LA PANDILLA SALVAJE' },
    { id: 266, titulo: 'EL BUFON DEL REY' },
    { id: 267, titulo: 'EL DIA DEL CHACAL' },
    { id: 268, titulo: 'EL BARON' },
    { id: 269, titulo: 'VESTIDA PARA MATAR' },
    { id: 270, titulo: 'AL PONERSE EL SOL' },
    { id: 271, titulo: 'RECORDANDOTE' },
    { id: 272, titulo: 'EL BAILE' },
    { id: 273, titulo: 'EL RECUENTRO' },
    { id: 274, titulo: 'PLACER DE VENGANZA' },
    { id: 275, titulo: 'EL CISNE' },
    { id: 276, titulo: 'ESTRELLAS FUGACES' },
    { id: 277, titulo: 'CAMPANAS ROJAS' },
    { id: 278, titulo: 'CON LOS MINUTOS CONTADOS' },
    { id: 279, titulo: 'RELACIONES DE SANGRE' },
    { id: 280, titulo: 'LAS TRUCHAS' },
    { id: 281, titulo: 'LAS MARIPOSAS SON LIBRES' },
    { id: 282, titulo: 'HEROES OLVIDADOS' },
    { id: 283, titulo: 'CAZADOR DE SOMBRAS' },
    { id: 284, titulo: 'EL COLOR DEL DINERO' },
    { id: 285, titulo: 'EL NEGRO ES UN COLOR BELLO' },
    { id: 286, titulo: 'DESDE RUSIA CON AMOR' },
    { id: 287, titulo: 'ANTES DEL AMANECER' },
    { id: 288, titulo: 'EL MURO' },
    { id: 289, titulo: 'LAS CHICAS VAN AL FRENTE' },
    { id: 290, titulo: 'EL ULTIMO TANGO DEL PAIS' },
    { id: 291, titulo: 'EL GRAN RUIDO EN LA NOCHE' },
    { id: 292, titulo: 'BRIGADA ASESINA' },
    { id: 293, titulo: 'CRIATURA' },
    { id: 294, titulo: 'HABIA UNA VEZ UN TREN' },
    { id: 295, titulo: 'LA COLMENA' },
    { id: 296, titulo: 'LA MARCA DEL ZORRO' },
    { id: 297, titulo: 'CIUDAD CORRUPTA' },
    { id: 298, titulo: 'HOTEL DEL TERROR' },
    { id: 299, titulo: 'RECUERDOS DE VERANO' },
    { id: 300, titulo: 'LO QUE EL VIENTO SE LLEVO' },
    { id: 301, titulo: 'EL TRITURADOR' },
    { id: 302, titulo: 'EL PERRO DEL INFIERNO' },
    { id: 303, titulo: 'BELLO COMO UN ARCANGEL' },
    { id: 304, titulo: 'CHICAS QUE TRABAJAN' },
    { id: 305, titulo: 'EL SILENCIO DEL NORTE' },
    { id: 306, titulo: 'MISION FATAL' },
    { id: 307, titulo: 'MUERTE EN INVIERNO' },
    { id: 308, titulo: 'EL MONOSABIO' },
    { id: 309, titulo: 'EL NUMERO UNO' },
    { id: 310, titulo: 'EL GOLPE' },
    { id: 311, titulo: 'LIBEREN A WILLY' },
    { id: 312, titulo: 'EL MENSAJERO DEL AMOR' },
    { id: 313, titulo: 'EL RAPTO' },
    { id: 314, titulo: 'DOCE DEL PATIBULO' },
    { id: 315, titulo: 'EL JINETE PALIDO' },
    { id: 316, titulo: 'FABRICA DE LOCURAS' },
    { id: 317, titulo: 'SUEÑOS DE TRIUNFO' },
    { id: 318, titulo: 'HABIA UNA VEZ UN CIRCO' },
    { id: 319, titulo: 'COCAINA LA CALLE DE LA DROGA' },
    { id: 320, titulo: 'DIAS DE IRA' },
    { id: 321, titulo: 'CHICLE CALIENTE' },
    { id: 322, titulo: 'EL ASALTO' },
    { id: 323, titulo: 'EL MOLINETE' },
    { id: 324, titulo: 'SIN SALIDA' },
    { id: 325, titulo: 'CUENTOS ASOMBROSOS' },
    { id: 326, titulo: 'LA NONNA'},
    { id: 327, titulo: 'LA NIÑA DEL GATO'},
    { id: 328, titulo: 'LA BELLA Y LA BESTIA'},
    { id: 329, titulo: 'CONTRABANDO'},
    { id: 330, titulo: 'EL HEROE DE LA FAMILIA'},
    { id: 331, titulo: 'CRIMENES DEL CORAZON'},
    { id: 332, titulo: 'EL GATO CON BOTAS'},
    { id: 333, titulo: 'LA TERCERA GUERRA MUNDIAL'},
    { id: 334, titulo: 'PESADILLA DEMONIACA'},
    { id: 335, titulo: 'POR GRACIA RECIBIDA'},
    { id: 336, titulo: 'POR QUIEN DOBLAN LAS CAMPANAS'},
    { id: 337, titulo: 'PIRATAS'},
    { id: 338, titulo: 'LINEA DE FUEGO'},
    { id: 339, titulo: 'ASESINEN AL PAYASO'},
    { id: 340, titulo: 'EL PORTERO DE NOCHE'},
    { id: 341, titulo: 'PRESA FACIL'},
    { id: 342, titulo: 'RETRATO DE UN ASESINO'},
    { id: 343, titulo: 'ROBO, HUYO Y LO PESCARON'},
    { id: 344, titulo: 'MAGNOLIAS DE ACERO'},
    { id: 345, titulo: 'EL GRAN ENGAÑO'},
    { id: 346, titulo: 'TERROR BAJO LA TIERRA'},
    { id: 347, titulo: 'EL JUGUETE'},
    { id: 348, titulo: 'LA PIEL'},
    { id: 349, titulo: 'EL PRINCIPE ENCANTADOR'},
    { id: 350, titulo: 'ATENTADO AL PODER'},
    { id: 351, titulo: 'FUEGO NEGRO'},
    { id: 352, titulo: 'CAMAS BLANDASS, BATALLAS DURAS'},
    { id: 353, titulo: 'CORAJE'},
    { id: 354, titulo: 'HERCULES'},
    { id: 355, titulo: 'EL BUFALO BLANCO'},
    { id: 356, titulo: 'EL ORACULO'},
    { id: 357, titulo: 'NAVIDADES BLANCAS'},
    { id: 358, titulo: 'LA LLAVE'},
    { id: 359, titulo: 'AGUILAS'},
    { id: 360, titulo: 'LA CUENTA FINAL'},
    { id: 361, titulo: 'MERCADO DE FUEGO'},
    { id: 362, titulo: 'EL REY Y YO'},
    { id: 363, titulo: 'ES MI HOMBRE'},
    { id: 364, titulo: 'RESCATE EN EL BARRIO CHINO'},
    { id: 365, titulo: 'GUERRA SILENCIOSA'},
    { id: 366, titulo: 'SOMOS TODOS INQUILINOS'},
    { id: 367, titulo: 'EL CANDIDATO'},
    { id: 368, titulo: 'LAS ARMAS DEL DIABLO'},
    { id: 369, titulo: 'LOS TRES CABALLEROS'},
    { id: 370, titulo: 'TRUENO ROJO'},
    { id: 371, titulo: 'EL MOUNTRUO DE LAS NIEVES'},
    { id: 372, titulo: 'COMO ELIMINAR A SU JEFE'},
    { id: 373, titulo: 'YO LA PEOR DE TODAS'},
    { id: 374, titulo: 'OPERACION DRAGON'},
    { id: 375, titulo: 'FUGA HACIA LA LIBERTAD'},
    { id: 376, titulo: 'EL EXTERMINADOR'},
    { id: 377, titulo: 'ENCUENTROS MUY CERCANOS'},
    { id: 378, titulo: 'ATRAPADO SIN SALIDA'},
    { id: 379, titulo: 'MI AMIGO EL DRAGON'},
    { id: 380, titulo: 'JUGANDO CON FUEGO'},
    { id: 381, titulo: 'LA TIERRA QUIETA'},
    { id: 382, titulo: 'MEDIANOCHE'},
    { id: 383, titulo: 'HAN ROBADO A MIS HIJOS'},
    { id: 384, titulo: 'EL ARCA DE NOE'},
    { id: 385, titulo: 'ARISTOCRATAS DEL CRIMEN'},
    { id: 386, titulo: 'METAMORFOSIS'},
    { id: 387, titulo: 'JUEGO SUCIO'},
    { id: 388, titulo: 'EL HUNDIMIENTO DEL TITANIC'},
    { id: 389, titulo: 'VIVIR Y MORIR EN LOS ANGELES'},
    { id: 390, titulo: 'TIEMPO MASACRE'},
    { id: 391, titulo: 'MUCHACHO LOBO'},
    { id: 392, titulo: 'SANGRE DE CONDOR'},
    { id: 393, titulo: 'EL PERRO'},
    { id: 394, titulo: 'LAS ESCLAVAS'},
    { id: 395, titulo: 'NOCHE INFERNAL'},
    { id: 396, titulo: 'LOS FIERECILLOS SE DIVIERTEN'},
    { id: 397, titulo: 'LA PESTE'},
    { id: 398, titulo: 'EL GRAN PECADOR'},
    { id: 399, titulo: 'RETOCER NUNCA RENDIRSE JAMAS'},
    { id: 400, titulo: 'LA HIENA'},
    { id: 401, titulo: 'RABINO Y EL PISTOLERO'},
    { id: 402, titulo: 'EL ABRAZO DE LA MUERTE'},
    { id: 403, titulo: 'BOMBARDEO'},
    { id: 404, titulo: 'EL FUGITIVO'},
    { id: 405, titulo: 'FLECHA ROTA'},
    { id: 406, titulo: 'MINUTOS ANTES'},
    { id: 407, titulo: 'SI TE DICEN QUE CAI'},
    { id: 408, titulo: 'HERMANOS ABRAZADOS'},
    { id: 409, titulo: 'LA MONTAÑA RUSA'},
    { id: 410, titulo: 'ANGELES GORDOS'},
    { id: 411, titulo: 'PASARON LAS GRULLAS'},
    { id: 412, titulo: 'EL HOMBRE PUMA'},
    { id: 413, titulo: 'ALAS'},
    { id: 414, titulo: 'LA ISLA DEL TERROR'},
    { id: 415, titulo: 'DONDE DUERMEN DOS DUERMEN TRES'},
    { id: 416, titulo: 'TANGO FEROZ'},
    { id: 417, titulo: 'LAS MINAS DEL REY'},
    { id: 418, titulo: 'ARROLLADA'},
    { id: 419, titulo: 'TE ACORDAS DE ANOCHE'},
    { id: 420, titulo: 'TIEMPO DE GLORIA'},
    { id: 421, titulo: 'CAMPAMENTO INFERNAL'},
    { id: 422, titulo: 'EL GENIO'},
    { id: 423, titulo: 'LOS GIRASOLES DE RUSIA'},
    { id: 424, titulo: 'EL PRINCIPE Y EL MENDIGO'},
    { id: 425, titulo: 'SESIONES PRIVADAS'},
    { id: 426, titulo: 'CONDENADA SIN SALIDA'},
    { id: 427, titulo: 'EL PRECIO DE LA FELICIDAD'},
    { id: 428, titulo: 'TARDE DE PERROS'},
    { id: 429, titulo: 'SE PRESUME INOCENTE'},
    { id: 430, titulo: 'PROFESION INFERNAL'},
    { id: 431, titulo: 'ACORRALADA'},
    { id: 432, titulo: 'EL DESEO LOCO'},
    { id: 433, titulo: 'EL EXPRESO DE MEDIANOCHE'},
    { id: 434, titulo: 'JUNTOS SON DINAMITA'},
    { id: 435, titulo: 'NACIDO PARA MATAR'},
    { id: 436, titulo: 'FIEBRE DE AMOR'},
    { id: 437, titulo: 'NUESTROS AÑOS FELICES'},
    { id: 438, titulo: 'EL PIRATA BOCANEGRA'},
    { id: 439, titulo: 'LAS PRISIONERAS'},
    { id: 440, titulo: 'LA CASA DE LAS SOMBRAS'},
    { id: 441, titulo: 'DOS PUÑOS CONTRA RIO'},
    { id: 442, titulo: 'DARSE CUENTA'},
    { id: 443, titulo: 'SUPERMAN'},
    { id: 444, titulo: 'PROCESO PENAL'},
    { id: 445, titulo: 'TERROR EN EL MENU'},
    { id: 446, titulo: 'FIEBRE DE UNA NOCHE DE VERANO'},
    { id: 447, titulo: 'LA NOCHE DE LOS LAPICES'},
    { id: 448, titulo: 'EL HOMBRE ARAÑA'},
    { id: 449, titulo: 'NOCHE DE NEW YORK'},
    { id: 450, titulo: 'LA TIENDITA DEL HORROR'},
    { id: 451, titulo: 'DESNUDO DE MUJER'},
    { id: 452, titulo: 'LA HISTORIA OFICIAL'},
    { id: 453, titulo: 'LA CANCION DEL VERDUGO'},
    { id: 454, titulo: 'PUEBLO MALDITO'},
    { id: 455, titulo: 'VEN VUELA CONMIGO'},
    { id: 456, titulo: 'EL BESO ANTE EL ESPEJO'},
    { id: 457, titulo: 'EL ARQUERO VERDE'},
    { id: 458, titulo: 'BELLEZA NEGRA'},
    { id: 459, titulo: 'RAICES PROFUNDAS'},
    { id: 460, titulo: 'DESAYUNO CON DIAMANTES'},
    { id: 461, titulo: 'EL LARGO Y CALIDO VERANO'},
    { id: 462, titulo: 'SUEÑOS ELECTRICOS'},
    { id: 463, titulo: 'OJO POR OJO'},
    { id: 464, titulo: 'MUERTE NUCLEAR'},
    { id: 465, titulo: 'ESPERANZA'},
    { id: 466, titulo: 'LAS LLAVES DEL REINO'},
    { id: 467, titulo: 'RUTAS DE VIOLENCIA'},
    { id: 468, titulo: 'UNA LUZ EN LA VENTANA'},
    { id: 469, titulo: 'HECHO EN PARIS'},
    { id: 470, titulo: 'DOS HERMANOS DOS DESTINOS'},
    { id: 471, titulo: 'INFINITO'},
    { id: 472, titulo: 'HISTOIA DE UN SOLDADO'},
    { id: 473, titulo: 'TAMBORES LEJANOS'},
    { id: 474, titulo: 'AL DIABLO CON ESTE TRABAJO'},
    { id: 475, titulo: 'Y LA NAVE VA...'},
    { id: 476, titulo: 'COLMILLO BLANCO'},
    { id: 477, titulo: 'EL HOMBRE MERCADO'},
    { id: 478, titulo: 'UN MES DE ABSTINENCIA'},
    { id: 479, titulo: 'ACUSADOS'},
    { id: 480, titulo: 'DULCES HORAS'},
    { id: 481, titulo: 'CAZADOR DE SERRPIENTES'},
    { id: 482, titulo: 'EL OCASO DE UNA ESTRELLA'},
    { id: 483, titulo: 'EL GORDO Y EL FLACO'},
    { id: 484, titulo: 'GIGANTE'},
    { id: 485, titulo: 'SECRETOS DE HOTEL'},
    { id: 486, titulo: 'BAJO SOSPECHA'},
    { id: 487, titulo: 'EL SEÑOR DE BLANCO'},
    { id: 488, titulo: 'LA MONTAÑA EMBRUJADA'},
    { id: 489, titulo: 'DIARIO INTIMO DE UNA MUJER CASADA'},
    { id: 490, titulo: 'EL DESTRIPADOR'},
    { id: 491, titulo: 'DE MENDIGO A MILLONARIO'},
    { id: 492, titulo: 'EL AMANTE'},
    { id: 493, titulo: 'EL MENSAJE'},
    { id: 494, titulo: 'EL DEMOLEDOR'},
    { id: 495, titulo: 'AL FINAL DE LAS ESCALERAS'},
    { id: 496, titulo: 'HOTEL DE SEÑORITAS'},
    { id: 497, titulo: 'PERDIDOS EN LA MONTAÑA'},
    { id: 498, titulo: 'CAMPEONES'},
    { id: 499, titulo: 'EL CENTINELA'},
    { id: 500, titulo: 'CASANOVA'},
    { id: 501, titulo: 'LA VIDA ROBADA'},
    { id: 502, titulo: 'JUEGO DE REYES'},
    { id: 503, titulo: 'COBRA'},
    { id: 504, titulo: 'LA MUJER PANTERA'}
]


//-----------------------------------------------------------------------------
const roulette = document.querySelector(".spinner");
const spinButton = document.querySelector('#spin');
let numeroRandom = 0
let tituloPeliculaRandom = 0


const actuarPelicula = document.querySelector('.actuarPelicula')
const btnClose = document.querySelector('#btnClose')



spinButton.addEventListener('click', ()=>{
    if(roulette.hasAttribute('id', 'girarSpinnerJs')){
        roulette.removeAttribute('id', 'girarSpinnerJs')
    }else{
        //----Animar (hacer girar la ruleta) (agregarle un estilo)
        roulette.setAttribute('id','girarSpinnerJs')
        //----Recorer el array, seleccionar un pelicula al azar por id (random)
        setTimeout(function(){
            numeroRandom = parseInt(Math.random() * nombrePeliculas.length)
            // console.log(numeroRandom)
            let pelicula = nombrePeliculas.filter(producto => producto.id == numeroRandom)
            // console.log(pelicula)
            let tituloPelicula = pelicula[0].titulo
            console.log(tituloPelicula)
            Swal.fire({
                icon: 'success',
                title: `${tituloPelicula}`,
                backdrop:`rgba(0,0,0, 0.8)`
            })
        }, 4500);
    }
})




















